# copied from som
shared:
  tickets_per_dollar: 5.0
  dollars_per_mean_hour: 2.0
  min_quality_multiplier: 1.0
  mean_quality_multiplier: 10.0
  max_quality_multiplier: 30.0
  lowest_dollar_per_hour: 0.3
  highest_dollar_per_hour: 6.0
  sb_min_dollar_per_hour: 1.0
